ES-829615-Azure-App-Service-WordtoPDF
syncfusion-content/fileformat-docs pull request #1143
Opened 2023-05-30 04:47 UTC by Venkateshmuruganandam

Hi All,
Added Subpages of Azure Function for Conver Word to PDF.

Regards
Venkatesh

2023-05-30 04:48 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1734/)<br/>**

2023-05-30 05:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1737/console)**

2023-05-30 05:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1737/)<br/>**

2023-05-30 08:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1738/)<br/>**

2023-05-30 08:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1739/console)**

2023-05-30 08:45 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1739/)<br/>**

2023-05-30 08:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1740/console)**

2023-05-30 08:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1740/)<br/>**

2023-05-30 08:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1741/console)**

2023-05-30 08:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1741/)<br/>**

2023-05-30 09:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1742/)<br/>**

2023-05-30 09:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1743/console)**

2023-05-30 09:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1743/)<br/>**

2023-05-30 09:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1744/console)**

2023-05-30 09:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1744/)<br/>**

2023-05-30 09:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1745/console)**

2023-05-30 09:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1745/)<br/>**

2023-05-30 09:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1746/console)**

2023-05-30 10:15 UTC, MohanaselvamJothi requested changes

2023-05-30 10:15 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Convert-Word-Document-to-PDF-Azure-App-Service-Linux.md
> +private void FontSettings_SubstituteFont(object sender, SubstituteFontEventArgs args)
Remove font handling related code.

2023-05-30 10:15 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Convert-Word-Document-to-PDF-Azure-App-Service-Linux.md
> +You can download a complete working sample from [GitHub](https://github.com/SyncfusionExamples/DocIO-Examples/tree/main/Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Azure/Azure_Functions/Azure
Change the link

2023-05-30 10:47 UTC, Venkateshmuruganandam commented on File-Formats-toc.html
> +									<a href="/file-formats/DocIO/Convert-Word-Document-to-PDF-Azure-App-Service-Linux">App Service(Linux)</a>
Updated

2023-05-30 10:56 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Azure-MainPage.md
> +<td>
Updated

2023-05-30 10:58 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Azure-MainPage.md
> +{{'[SkiaSharp.NativeAssets.Linux](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux)' | markdownify}}<br/>{{'[HarfBuzzSharp.NativeAssets.Linux](https://www.nuget.org/packages/HarfBuzzSharp.
Updated

2023-05-30 10:59 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Azure-MainPage.md
> +Azure Functions v4 (.NET 6.0, 7.0)<br/></td><td>
updated

2023-05-30 10:59 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Azure-MainPage.md
> +Azure Functions v1 (.NET Framework)<br/></td><td>
Updated

2023-05-30 11:01 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Convert-Word-Document-to-PDF-Azure-App-Service-Linux.md
> +Step 4: Install the following **Nuget packages**.
Updated

2023-05-30 11:01 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Convert-Word-Document-to-PDF-Azure-App-Service-Linux.md
> +NuGet package as a reference to your .NET Core application from [Nuget.org](https://www.nuget.org/).
Updated

2023-05-30 11:04 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Convert-Word-Document-to-PDF-Azure-App-Service-Linux.md
> +private void FontSettings_SubstituteFont(object sender, SubstituteFontEventArgs args)
Updated

2023-05-30 11:07 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Convert-Word-Document-to-PDF-Azure-App-Service-Linux.md
> +![Configure your new project](Azure_Images/App_Service_Linux/Configure_Project_WordtoPDF.png)
Updated

2023-05-30 11:22 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1749/console)**

2023-05-30 11:24 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1750/console)**

2023-05-30 11:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1750/console)**

2023-05-30 11:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1750/)<br/>**

2023-05-30 13:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1756/console)**

2023-05-30 13:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1757/console)**

2023-05-31 09:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1776/)<br/>**

2023-05-31 09:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1777/console)**

2023-05-31 09:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1777/)<br/>**

2023-05-31 09:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1778/console)**

2023-05-31 10:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1779/console)**

2023-05-31 10:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1779/)<br/>**

2023-05-31 10:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1780/console)**

2023-05-31 10:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1782/console)**

2023-05-31 10:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1782/)<br/>**

2023-05-31 10:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1783/console)**

2023-05-31 10:14 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-829615-Azure-App-Service-WordtoPDF](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1783/)<br/>**

2023-05-31 10:25 UTC, MohanaselvamJothi approved these changes

2023-05-31 10:25 UTC, merged