SEO-172146 - Presentation duplicate description
syncfusion-content/fileformat-docs pull request #1146
Opened 2023-05-30 13:30 UTC by Sharly-Atieno

Hi @Aishwarya-Ganesan,
Kindly review the changes for duplicate description.

Regards,
Sharly A.

2023-05-30 13:32 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-172146-Presentation-](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1758/console)**

2023-05-30 13:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172146-Presentation-](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1758/console)**

2023-05-30 13:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172146-Presentation-](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1758/)<br/>**

2023-05-31 04:54 UTC, gowthamanthavasiyappan requested changes
Commented

2023-05-31 04:54 UTC, gowthamanthavasiyappan commented on File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md
> +description: Learn here all about create,read and edit support in Syncfusion ASP.NET Core PowerPoint control, its features, and more.
Revert this description.

2023-05-31 05:57 UTC, Sharly-Atieno commented on File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md
> +description: Learn here all about create,read and edit support in Syncfusion ASP.NET Core PowerPoint control, its features, and more.
reverted

2023-05-31 05:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172146-Presentation-](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1765/)<br/>**

2023-06-02 04:56 UTC, gowthamanthavasiyappan approved these changes
Approved

2023-06-02 05:04 UTC, Girija-Rajendran approved these changes

2023-06-02 05:04 UTC, merged