ES-822436-Find and Replace using Regex
syncfusion-content/fileformat-docs pull request #1175
Opened 2023-06-07 08:49 UTC by Venkateshmuruganandam

2023-06-07 08:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-822436-Find-and-Replace-Regex](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1860/console)**

2023-06-08 05:45 UTC, florenceliliana requested changes
The content review is completed.

2023-06-08 05:45 UTC, florenceliliana commented on File-Formats/Presentation/Working-with-find-and-replace.md
> +The following code example illustrates how to find all the occurrences of a pattern of text using Regex pattern and replace it with other text.
The following code example illustrates how to find all the occurrences of a pattern of text using the Regex pattern and replace it with other text.

2023-06-08 05:45 UTC, florenceliliana commented on File-Formats/Presentation/Working-with-find-and-replace.md
> +//Load or open an PowerPoint Presentation.
//Load or open a PowerPoint Presentation.

2023-06-08 05:45 UTC, florenceliliana commented on File-Formats/Presentation/Working-with-find-and-replace.md
> +        //Find all the occurrences of given pattern of text in the PowerPoint presentation using Regex.
//Find all the occurrences of a given pattern of text in the PowerPoint presentation using Regex.

2023-06-08 05:45 UTC, florenceliliana commented on File-Formats/Presentation/Working-with-find-and-replace.md
> +    //Find all the occurrences of given pattern of text in the PowerPoint presentation using Regex.
//Find all the occurrences of a given pattern of text in the PowerPoint presentation using Regex.

2023-06-08 05:45 UTC, florenceliliana commented on File-Formats/Presentation/Working-with-find-and-replace.md
> +The following code example illustrates how to find all the occurrences of a pattern of text using Regex pattern and highlight it.
The following code example illustrates how to find all the occurrences of a pattern of text using a Regex pattern and highlight it.

2023-06-08 05:45 UTC, florenceliliana commented on File-Formats/Presentation/Working-with-find-and-replace.md
> +        //Find all the occurrences of given pattern of text in the PowerPoint presentation using Regex.
//Find all the occurrences of a given pattern of text in the PowerPoint presentation using Regex.

2023-06-08 05:45 UTC, florenceliliana commented on File-Formats/Presentation/Working-with-find-and-replace.md
> +    //Find all the occurrences of given pattern of text in the PowerPoint presentation using Regex.
//Find all the occurrences of a given pattern of text in the PowerPoint presentation using Regex.

2023-06-08 06:09 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-822436-Find-and-Replace-Regex](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1866/console)**

2023-06-08 06:11 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1866/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-06-08 06:12 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-822436-Find-and-Replace-Regex](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1867/console)**

2023-06-08 06:13 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1867/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-06-08 06:14 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-822436-Find-and-Replace-Regex](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1869/console)**

2023-06-08 06:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-822436-Find-and-Replace-Regex](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1869/console)**

2023-06-08 06:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-822436-Find-and-Replace-Regex](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1869/)<br/>**

2023-06-08 07:49 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-06-08 07:53 UTC, merged