ES-831427_Subpage_Added_Azure_Function_for_Convert_WordtoImage
syncfusion-content/fileformat-docs pull request #1186
Opened 2023-06-12 13:31 UTC by Venkateshmuruganandam

Hi All,
Sub-page add Azure Functions both v1 and v4 for convert Word to Image.

Regards
Venkatesh

2023-06-14 12:51 UTC, Suriya-Balamurugan requested changes

2023-06-14 12:51 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v1.md
> +
Remove unwanted empty lines

2023-06-14 13:05 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v1.md
> +description: Convert Word document to Image in Azure Functions v1 using .NET Word (DocIO) library  without Microsoft Word or interop dependencies.
remove empty space

2023-06-14 13:05 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v1.md
> +Syncfusion DocIO is a [.NET Word library](https://www.syncfusion.com/document-processing/word-framework/net/word-library) used to create, read, edit and **convert Word documents** programmatically wi
Add full stop

2023-06-14 13:06 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v4.md
> +
Remove unwanted empty line

2023-06-15 06:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Es-831427-Azure_Functions_WordtoImage](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1918/console)**

2023-06-15 06:04 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v4.md
> +
updated

2023-06-15 06:04 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v1.md
> +Syncfusion DocIO is a [.NET Word library](https://www.syncfusion.com/document-processing/word-framework/net/word-library) used to create, read, edit and **convert Word documents** programmatically wi
updated

2023-06-15 06:04 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v1.md
> +description: Convert Word document to Image in Azure Functions v1 using .NET Word (DocIO) library  without Microsoft Word or interop dependencies.
updated

2023-06-15 06:04 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v1.md
> +
updated

2023-06-15 06:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Es-831427-Azure_Functions_WordtoImage](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1918/)<br/>**

2023-06-15 06:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Es-831427-Azure_Functions_WordtoImage](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1919/)<br/>**

2023-06-15 11:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Es-831427-Azure_Functions_WordtoImage](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1932/)<br/>**

2023-06-15 11:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Es-831427-Azure_Functions_WordtoImage](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1933/console)**

2023-06-15 11:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Es-831427-Azure_Functions_WordtoImage](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1933/)<br/>**

2023-06-15 12:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Es-831427-Azure_Functions_WordtoImage](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1934/console)**

2023-06-15 12:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Es-831427-Azure_Functions_WordtoImage](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1934/)<br/>**

2023-06-15 12:09 UTC, MohanaselvamJothi approved these changes

2023-06-15 12:14 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-06-15 12:15 UTC, merged