ES-842155 Find and add comments using regex
syncfusion-content/fileformat-docs pull request #1400
Opened 2023-08-09 06:58 UTC by Venkateshmuruganandam

Hi All,
UG draft work completed for Find and add comments using regex in DocIO.

Regards
Venkatesh

2023-08-09 06:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-842155-Find-and-add-comments](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2368/console)**

2023-08-09 06:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-842155-Find-and-add-comments](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2368/)<br/>**

2023-08-09 07:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-842155-Find-and-add-comments](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2369/console)**

2023-08-09 07:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-842155-Find-and-add-comments](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2369/)<br/>**

2023-08-09 09:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-842155-Find-and-add-comments](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2372/console)**

2023-08-09 12:51 UTC, M-A32 requested changes

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +                //Adds comment to a paragraph.
//Add comment to a paragraph.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +        //Create file stream.
//Create the file stream.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +            //Save the Word document to file stream.
//Save the Word document to the file stream.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +            //Get the found text as single text range.
//Get the found text as a single text range.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +                //Get the found text as single text range.
//Get the found text as a single text range.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +                //Set the date and time for comment.
//Set the date and time for the comment.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +            //Adds comment to a paragraph.
//Add comment to a paragraph.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +            //Set the date and time for comment.
//Set the date and time for the comment.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +        ' Add a comment to a paragraph.
' Add a comment to the paragraph.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +        //Find all occurrence of a particular text end with comma in the document using regex.
//Find all occurrence of a particular text ending with comma in the document using regex.

2023-08-09 12:51 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Comments.md
> +    //Find all occurrence of a particular text end with comma in the document using regex.
//Find all occurrence of a particular text ending with comma in the document using regex.

2023-08-09 13:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-842155-Find-and-add-comments](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2373/console)**

2023-08-09 13:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-842155-Find-and-add-comments](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2373/)<br/>**

2023-08-10 09:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-842155-Find-and-add-comments](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2378/console)**

2023-08-10 09:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-842155-Find-and-add-comments](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2378/)<br/>**

2023-08-11 05:18 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-08-11 05:27 UTC, MohanaselvamJothi approved these changes

2023-08-11 05:27 UTC, merged