UG-846272: volume 3 features UG
syncfusion-content/fileformat-docs pull request #1448
Opened 2023-09-04 12:12 UTC by Sri-hari-haran-g

2023-09-04 12:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG-846272](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2463/console)**

2023-09-04 12:14 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG-846272](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2463/)<br/>**

2023-09-05 03:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG-846272](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2468/console)**

2023-09-05 03:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG-846272](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2468/)<br/>**

2023-09-05 07:39 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Working-with-OCR/Features.md
> +new
Remove unwanted lines

2023-09-05 07:42 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine provides the support for inject the custom CSS to be applied in HTML or URL before rendering to PDF.
Use this - "The Blink rendering engine supports the injection of custom CSS to be applied to HTML or a URL before rendering it into a PDF document using the 'Css' property of the 'BlinkConverterSettings' class."

2023-09-05 07:43 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine provides the support for inject the custom CSS to be applied in HTML or URL before rendering to PDF.
Provide API link for BlinkConverterSettings class

2023-09-05 07:43 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +
Remove unwanted spaces

2023-09-05 07:45 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine provides the support for inject the custom JavaScript to be applied in HTML or URL before rendering to PDF.
Use this - "The Blink rendering engine offers support for injecting custom JavaScript to be applied to HTML or a URL before rendering it into a PDF document using the 'JavaScript' property of the 'BlinkConverterSettings' class."

2023-09-05 07:45 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine provides the support for inject the custom JavaScript to be applied in HTML or URL before rendering to PDF.
Provide API link for BlinkConverterSettings class

2023-09-05 07:45 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +
Remove unwanted spaces

2023-09-05 07:46 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine provides support for Reuse the Browser Process to optimize the HTML to PDF performance of multiple operations.
The Blink rendering engine provides support for reusing the browser process to optimize the HTML to PDF performance for multiple operations using the 'ReuseBrowserProcess' property of the 'HtmlToPdfConverter' class.

2023-09-05 08:32 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine provides support for reusing the browser process to optimize the HTML to PDF performance for multiple operations using the 'ReuseBrowserProcess' property of the 'HtmlToPdfC
Add link for HtmlToPdfConverter class

2023-09-05 08:34 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +## Inject Custom JavaScript
Change the title as "Inject custom JavaScript"

2023-09-05 08:35 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Working-with-OCR/Features.md
> +
Remove the space between sentence

2023-09-05 08:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG-846272](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2472/console)**

2023-09-05 08:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG-846272](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2472/)<br/>**

2023-09-05 08:57 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Working-with-OCR/Features.md
> +For Getting the Image rotation angle, you can rotate the image with 4 angles (0,90,180,360) from OCR Processor. This feature is working in multiple Images and multiple pages. The following code sampl
Add full stop in end of sentence

2023-09-05 09:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG-846272](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2473/console)**

2023-09-05 11:56 UTC, florenceliliana requested changes
The content review is completed.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine supports the injection of custom CSS to be applied to HTML or a URL before rendering it into a PDF document using the 'Css' property of the [BlinkConverterSettings](https:/
The Blink rendering engine supports the injection of custom CSS to be applied to the HTML or a URL before rendering it into a PDF document using the 'CSS' property of the [BlinkConverterSettings](https://help.syncfusion.com/cr/file-formats/Syncfusion.HtmlConverter.BlinkConverterSettings.html) class.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +//Initialize HTML to PDF converter.
//Initialize the HTML to PDF converter.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +//Set custom CSS
//Set the custom CSS.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +//Convert URL to PDF document.
//Convert the URL to a PDF document.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +//Set Blink viewport size.
//Set the Blink viewport size.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +'Initialize HTML to PDF converter.
'Initialize the HTML to a PDF converter.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +'Convert URL to PDF document.
'Convert the URL to a PDF document.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine offers support for injecting custom JavaScript to be applied to HTML or a URL before rendering it into a PDF document using the 'JavaScript' property of the [BlinkConverter
The Blink rendering engine offers support for injecting custom JavaScript to be applied to the HTML or a URL before rendering it into a PDF document using the 'JavaScript' property of the [BlinkConverterSettings](https://help.syncfusion.com/cr/file-formats/Syncfusion.HtmlConverter.BlinkConverterSettings.html) class.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +//Initialize HTML to PDF converter.
//Initialize the HTML to a PDF converter.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +//Set Blink viewport size.
//Set the Blink viewport size.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +//Set Custom JavaScript
//Set the Custom JavaScript.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +//Convert URL to PDF document.
//Convert the URL to a PDF document.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +'Initialize HTML to PDF converter.
'Initialize the HTML to a PDF converter.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +'Set Blink viewport size.
'Set the Blink viewport size.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +'Set Custom JavaScript
'Set the Custom JavaScript.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +'Convert URL to PDF document.
'Convert the URL to a PDF document.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine provides support for reusing the browser process to optimize the HTML to PDF performance for multiple operations using the 'ReuseBrowserProcess' property of the [HtmlToPdfC
The Blink rendering engine provides support for reusing the browser process to optimize the HTML to a PDF performance for multiple operations using the 'ReuseBrowserProcess' property of the [HtmlToPdfConverter](https://help.syncfusion.com/cr/file-formats/Syncfusion.HtmlConverter.HtmlToPdfConverter.html) class.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +//Initialize HTML to PDF converter.
//Initialize the HTML to a PDF converter.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +    //Convert URL to PDF document.
//Convert the URL to a PDF document.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Working-with-OCR/Features.md
> +For Getting the Image rotation angle, you can rotate the image with 4 angles (0,90,180,360) from OCR Processor. This feature is working in multiple Images and multiple pages. The following code sampl
To get the Image rotation angle, you can rotate the image with 4 angles (0,90,180, and 360) from the OCR Processor. This feature works in multiple Images and multiple pages. The following code sample illustrates support for the Image Rotation angle from the OCR Processor.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Working-with-OCR/Features.md
> +    //Get stream from an image file.
//Get the stream from an image file.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Working-with-OCR/Features.md
> +    //Set OCR language to process.
//Set the OCR language to process.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Working-with-OCR/Features.md
> +    //Set OCR language.
//Set the OCR language.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Working-with-OCR/Features.md
> +    //Sets Unicode font to preserve the Unicode characters in a PDF document.
//Set the Unicode font to preserve the Unicode characters in a PDF document.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Working-with-OCR/Features.md
> +    'Get stream from an image file.
'Get the stream from an image file.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Working-with-OCR/Features.md
> +    'Set OCR language to process.
'Set the OCR language to process.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Working-with-OCR/Features.md
> +    'Set OCR language.
'Set the OCR language.

2023-09-05 11:56 UTC, florenceliliana commented on File-Formats/PDF/Working-with-OCR/Features.md
> +    'Sets Unicode font to preserve the Unicode characters in a PDF document.
'Set the Unicode font to preserve the Unicode characters in a PDF document.

2023-09-05 12:25 UTC, florenceliliana approved these changes
Approved.

2023-09-06 04:18 UTC, SowmiyaLoganathan approved these changes

2023-09-08 04:29 UTC, PrakashViswanath requested changes

2023-09-08 04:29 UTC, PrakashViswanath commented on File-Formats/PDF/Convert-HTML-To-PDF/features.md
> +The Blink rendering engine supports the injection of custom CSS to be applied to HTML or a URL before rendering it into a PDF document using the 'CSS' property of the [BlinkConverterSettings](https:/
'CSS'  to  'Css'

2023-09-08 04:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG-846272](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2492/console)**

2023-09-08 04:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG-846272](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2492/)<br/>**

2023-09-08 04:40 UTC, PrakashViswanath approved these changes
The changes are fine.

2023-09-08 04:40 UTC, merged