ES-843418 - Update the content in PPTX to Image
syncfusion-content/fileformat-docs pull request #1454
Opened 2023-09-07 05:52 UTC by Venkateshmuruganandam

<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/843418">Update content in PPTX to Image </a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Change the word worksheet to PowerPoint document in assembly required
</td>
</tr>

</table>

Regards,
Venkatesh

2023-09-07 05:53 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-843418-assembly-required-change](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2488/console)**

2023-09-07 05:53 UTC, MohanaselvamJothi approved these changes

2023-09-07 05:54 UTC, MohanaselvamJothi requested changes

2023-09-07 05:54 UTC, MohanaselvamJothi commented on File-Formats/Presentation/Presentation-to-image.md
> +Refer to the following links for assemblies required based on platforms to convert the PowerPoint document to image.
PowerPoint Presentation to image

2023-09-07 05:56 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2488/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-09-07 05:56 UTC, Venkateshmuruganandam commented on File-Formats/Presentation/Presentation-to-image.md
> +Refer to the following links for assemblies required based on platforms to convert the PowerPoint document to image.
updated

2023-09-07 05:57 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-843418-assembly-required-change](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2489/console)**

2023-09-07 06:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-843418-assembly-required-change](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2489/console)**

2023-09-07 06:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-843418-assembly-required-change](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2488/console)**

2023-09-07 06:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-843418-assembly-required-change](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2488/)<br/>**

2023-09-07 06:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-843418-assembly-required-change](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2489/)<br/>**

2023-09-11 10:12 UTC, MohanaselvamJothi approved these changes

2023-09-11 10:12 UTC, merged