847609: Need to update UG documentation in HTMLTOPDF section
syncfusion-content/fileformat-docs pull request #1468
Opened 2023-09-14 06:56 UTC by Sri-hari-haran-g

2023-09-14 06:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [847609](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2525/console)**

2023-09-14 06:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [847609](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2525/)<br/>**

2023-09-14 08:40 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
> +Ex path: <i>D:\HTMl-to-PDF\HTMl-to-PDF\bin\Debug\net7.0\runtimes\win-x64\native</i>
Add code example here

2023-09-14 08:40 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
> +you can set BlinkPath if you need to set the Path explicitly
If you require explicit path setting, you can establish BlinkPath.

2023-09-14 08:41 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
> +Make sure that after installing the NuGet package and building, the 'runtimes' folder will be copied automatically.
Ensure that upon NuGet package installation and building, the 'runtimes' folder is automatically copied.

2023-09-14 08:41 UTC, SowmiyaLoganathan commented on File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
> +<td>The exception may occurs if the '<i>runtimes</i>' folder doesn't get copied properly from the NuGet folder.
The exception may occur if the '<i>runtimes</i>' folder isn't copied correctly from the NuGet folder.

2023-09-14 09:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [847609](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2532/console)**

2023-09-14 09:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [847609](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2532/)<br/>**

2023-09-14 10:58 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [847609](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2536/console)**

2023-09-14 11:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [847609](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2536/console)**

2023-09-14 11:48 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [847609](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2536/)<br/>**

2023-09-21 05:25 UTC, PrakashViswanath requested changes

2023-09-21 05:25 UTC, PrakashViswanath commented on File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
> +Ex path: <i>C:\HtmlConversion\HTMl-to-PDF\HTMl-to-PDF\bin\Debug\net7.0\runtimes\win-x64\native\BlinkBinaries</i>
C:\HtmlConversion\HTMl-to-PDF\HTMl-to-PDF\bin\Debug\net7.0\runtimes\win-x64\native\

2023-09-21 05:25 UTC, PrakashViswanath commented on File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
> +Ensure that upon NuGet package installation and building, the 'runtimes' folder is automatically copied.
Ensure that the runtimes folder is copied properly to bin folder of the application from NuGet package location.

2023-09-21 05:25 UTC, PrakashViswanath commented on File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
> +If you require explicit path setting, you can establish BlinkPath.
You can set the runtimes folder path explicitly in BlinkPath property in BlinkConverterSettings class.

2023-09-21 06:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [847609](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2573/console)**

2023-09-21 06:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [847609](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2573/)<br/>**

2023-09-21 09:18 UTC, merged