WF-61451 - Add information about to edit content control text in the Word document
syncfusion-content/fileformat-docs pull request #15
Opened 2021-11-23 04:45 UTC by ManikandanRavichandranSync

WF-61451 - Add information about to edit content control text in the Word document

2022-02-14 16:53 UTC, ManikandanRavichandranSync commented
Rebuild

2022-02-14 16:55 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/241/artifact/cireports/)<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/241/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/241/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/241/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/241/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/241/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/241/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/241/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-23 06:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/251/console)**

2022-02-23 06:26 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/251/artifact/cireports/)<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/251/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/251/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/251/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/251/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/251/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/251/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/251/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-23 06:35 UTC, DeepakRajSundar commented
rebuild

2022-02-23 06:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/254/console)**

2022-02-24 06:00 UTC, kannans24 commented
rebuild

2022-02-24 06:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/257/console)**

2022-02-24 06:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/257/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/257/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/257/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/257/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/257/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/257/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/257/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-24 11:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/262/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/262/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/262/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/262/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/262/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/262/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/262/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-24 11:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/263/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/263/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/263/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/263/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/263/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/263/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/263/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-28 05:05 UTC, MohanaselvamJothi requested changes

2022-02-28 05:05 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-With-Content-Controls.md
> +## Edit Content Control Text
Change the title as "Edit inline content text"

2022-02-28 05:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/281/console)**

2022-02-28 05:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/281/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/281/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/281/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/281/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/281/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/281/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/281/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-28 05:37 UTC, MohanaselvamJothi approved these changes

2022-02-28 05:37 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-With-Content-Controls.md
> +	//Remove exiting items and add new text range with required text
Check the indent of xml comment

2022-02-28 05:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/283/console)**

2022-02-28 05:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/283/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/283/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/283/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/283/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/283/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/283/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/283/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-28 05:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/284/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/284/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/284/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/284/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/284/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/284/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/284/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-28 05:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/285/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/285/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/285/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/285/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/285/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/285/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/285/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-28 06:14 UTC, MohanaselvamJothi approved these changes

2022-02-28 06:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/286/console)**

2022-02-28 06:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-61451-EditContentControlText](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/286/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/286/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/286/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/286/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/286/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/286/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/286/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-02-28 08:58 UTC, MohanaselvamJothi approved these changes

2022-02-28 08:58 UTC, merged