ES- 852595 Revamp Chart in DocIO
syncfusion-content/fileformat-docs pull request #1569
Opened 2023-10-18 13:50 UTC by Venkateshmuruganandam

Hi All,
Added the subpage for working with chart.

Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/852595/

Regards
Venkatesh

2023-10-18 13:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2701/console)**

2023-10-18 13:52 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2702/console)**

2023-10-18 13:53 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2702/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-10-18 13:54 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2703/console)**

2023-10-18 13:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2703/console)**

2023-10-18 13:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2703/)<br/>**

2023-10-19 09:52 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2704/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-10-19 09:52 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2704/console)**

2023-10-19 09:53 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2705/console)**

2023-10-19 10:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2705/console)**

2023-10-19 10:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2704/)<br/>**

2023-10-19 10:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2705/)<br/>**

2023-10-23 06:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2709/)<br/>**

2023-10-23 06:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2710/console)**

2023-10-23 06:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2710/)<br/>**

2023-10-23 08:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2711/console)**

2023-10-23 08:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2711/)<br/>**

2023-10-23 09:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2712/console)**

2023-10-23 09:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2712/)<br/>**

2023-10-23 10:13 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2713/console)**

2023-10-23 10:19 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2713/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-10-23 10:20 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2714/console)**

2023-10-23 10:26 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2714/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-10-23 10:27 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2715/console)**

2023-10-23 10:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2715/console)**

2023-10-23 10:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2715/)<br/>**

2023-10-24 05:56 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2723/console)**

2023-10-24 09:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2730/)<br/>**

2023-10-24 11:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2731/console)**

2023-10-24 11:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2731/)<br/>**

2023-10-24 11:26 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2732/console)**

2023-10-24 11:26 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2732/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-10-24 11:27 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2733/console)**

2023-10-24 11:31 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2734/console)**

2023-10-24 11:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2734/console)**

2023-10-24 11:41 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2734/)<br/>**

2023-10-24 11:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2735/console)**

2023-10-24 11:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2735/)<br/>**

2023-10-25 05:39 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2741/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-10-25 05:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2742/console)**

2023-10-25 05:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2742/)<br/>**

2023-10-25 05:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2743/console)**

2023-10-25 05:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2743/)<br/>**

2023-10-25 05:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2744/console)**

2023-10-25 05:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2744/)<br/>**

2023-10-25 05:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2745/console)**

2023-10-25 05:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2745/)<br/>**

2023-10-25 07:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2747/console)**

2023-10-25 07:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2747/)<br/>**

2023-10-25 12:03 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2749/console)**

2023-10-25 12:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2749/console)**

2023-10-25 12:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2749/)<br/>**

2023-10-26 05:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2754/console)**

2023-10-26 05:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2754/)<br/>**

2023-10-26 05:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2755/console)**

2023-10-26 05:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2755/)<br/>**

2023-10-26 08:17 UTC, M-A32 requested changes
I have completed the review.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Axis.md
> +//MaxCross in axis
//MaxCross in axis.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Axis.md
> +The following code snippet illustrates how to customize the border of Horizontal and vertical category axis.
The following code sample illustrates how to customize the border of Horizontal and vertical category axis.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Axis.md
> +The following code snippet illustrates how to set the number format in the axis.
The following code sample illustrates how to set the number format in the axis.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Axis.md
> +The following code snippet illustrates how to hide or show major and minor gridlines.
The following code sample illustrates how to hide or show major and minor gridlines.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Axis.md
> +The following code snippet illustrates how to customize secondary value axis in chart.
The following code sample illustrates how to customize secondary value axis in chart.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Chart-Area.md
> +The following code snippet illustrates how to make transparency in chart area.
The following code sample illustrates how to make transparency in chart area.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Chart-Area.md
> +The complete code snippet illustrating the above options is shown below.
The complete code sample illustrating the above options is shown below.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Chart-Title.md
> +The following code snippet illustrates how to customize the chart title area.
The following code sample illustrates how to customize the chart title area.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Data-Lables.md
> +The following code snippet illustrates how to visible the data label in chart.
The following code sample illustrates how to visible the data label in chart.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Data-Lables.md
> +// Set the size of the data labels
// Set the size of the data labels.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Data-Lables.md
> +The following code snippet illustrates how to set the position of the data label in chart.
The following code sample illustrates how to set the position of the data label in chart.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Data-Lables.md
> +The following code snippet illustrates how to resize the data label in chart.
The following code sample illustrates how to resize the data label in chart.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Legend.md
> +description: Learn how to modify the appearance of legend in a chart in a  Word document using Syncfusion .NET Core Word (DocIO) library without Microsoft Word.
description: Learn how to modify the appearance of legend in a chart in a Word document using Syncfusion .NET Core Word (DocIO) library without Microsoft Word.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Legend.md
> +Legends are visual **pictorial** hints that provide a viewer information that helps them understand an chart. Using Syncfusion [.NET Core Word (DocIO)](https://www.syncfusion.com/document-processing/
Legends are visual **pictorial** hints that provide a viewer information that helps them understand an chart. Using Syncfusion [.NET Core Word (DocIO)](https://www.syncfusion.com/document-processing/word-framework/net-core/word-library) library, you can customize the **legend** in the chart.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Legend.md
> +The following code snippet illustrates how to set the legend position in chart.
The following code sample illustrates how to set the legend position in chart.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Legend.md
> +The following code snippet illustrates how to modify the border of the legend in chart.
The following code sample illustrates how to modify the border of the legend in chart.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Legend.md
> +The following code snippet illustrates how to hide the legend in chart.
The following code sample illustrates how to hide the legend in chart.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Legend.md
> +//Manually positioning chart legend area using Layout
//Manually positioning chart legend area using Layout.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Legend.md
> +//Manually positioning chart legend area using Manual Layout
//Manually positioning chart legend area using Manual Layout.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Legend.md
> +//Manually resizing chart legend area using Manual Layout
//Manually resizing chart legend area using Manual Layout.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Legend.md
> +//Manually resizing chart legend area using Layout
//Manually resizing chart legend area using Layout.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Plot-Area.md
> +title: Modify the appearance of plot area | Syncfusion
title: Modify the Appearance of Plot Area | Syncfusion

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Plot-Area.md
> + //Sets fill type and color
//Sets fill type and color.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Plot-Area.md
> +The following code snippet shows how to make transparency in plot area.
The following code sample shows how to make transparency in plot area.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Plot-Area.md
> +//Open an existing document from file system through constructor of WordDocument class
//Open an existing document from file system through constructor of WordDocument class.

2023-10-26 08:17 UTC, M-A32 commented on File-Formats/DocIO/Working-with-Charts/Format-Series.md
> +//Set HasHighLowLines property to true.
//Set the HasHighLowLines property to true.

2023-10-26 10:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2757/console)**

2023-10-26 10:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2757/)<br/>**

2023-10-26 11:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2758/console)**

2023-10-26 11:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2758/)<br/>**

2023-10-26 12:35 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2759/console)**

2023-10-26 12:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2759/console)**

2023-10-26 12:42 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2759/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-10-26 12:43 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2760/console)**

2023-10-26 12:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2760/console)**

2023-10-26 13:25 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Format-Axis.md
> +---
modified

2023-10-26 13:25 UTC, Venkateshmuruganandam commented on File-Formats/DocIO/Format-Axis.md
> +description: Learn how to modify the appearance of axes in a chart using Syncfusion .NET Core Word (DocIO) library without Microsoft Word or interop dependencies.
Modified

2023-10-26 13:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2761/console)**

2023-10-26 13:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-852595-Revamp-Chart](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/2761/)<br/>**

2023-10-26 13:55 UTC, merged

2023-10-31 13:09 UTC, florenceliliana reviewed
The content review is completed.

2023-10-31 13:09 UTC, florenceliliana commented on File-Formats/DocIO/Working-with-Charts/Format-Chart-Title.md
> +The complete code snippet illustrating the above options is shown below.
The complete code sample illustrating the above options is shown as follows.

2023-10-31 13:09 UTC, florenceliliana commented on File-Formats/DocIO/Working-with-Charts/Format-Chart-Title.md
> +The following code snippet illustrates how to resize the chart title area.
The following code sample illustrates how to resize the chart title area.

2023-10-31 13:09 UTC, florenceliliana commented on File-Formats/DocIO/Working-with-Charts/Format-Chart-Title.md
> +The following code snippet illustrates how to customize the chart title area.
The following code sample illustrates how to customize the chart title area.

2023-10-31 13:09 UTC, florenceliliana commented on File-Formats/DocIO/Working-with-Charts/Format-Chart-Title.md
> +The following code snippet illustrates how to set the chart title name.
The following code sample illustrates how to set the chart title name.