ES 861360 Modify the syntax in LaTeX
syncfusion-content/fileformat-docs pull request #1732
Opened 2023-12-27 07:29 UTC by Venkateshmuruganandam

HI All
Modify the syntax in LaTeX.

Regards
Venkatesh

2023-12-27 07:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/3027/console)**

2023-12-27 07:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/3027/)<br/>**

2023-12-27 10:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/3028/console)**

2023-12-27 10:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/3028/)<br/>**

2023-12-27 10:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/3029/console)**

2023-12-27 11:00 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/3029/)<br/>**

2023-12-27 13:33 UTC, MathanKumarVaradhaRajaPerumal requested changes

2023-12-27 13:33 UTC, MathanKumarVaradhaRajaPerumal commented on File-Formats/DocIO/Working-with-LaTeX.md
> +document.LastParagraph.AppendMath(@"\boxed{{x}^2+{y}^2={z}^2}");
Add curly braces for 2 also.

2023-12-27 13:33 UTC, MathanKumarVaradhaRajaPerumal commented on File-Formats/DocIO/Working-with-LaTeX.md
> +document.LastParagraph.AppendMath(@"{_40^{20}}100");
Please modify properly it is invalid syntax

2023-12-28 06:09 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/2/console)**

2023-12-28 06:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/2/console)**

2023-12-28 06:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/2/)<br/>**

2023-12-28 06:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/4/console)**

2023-12-28 06:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/4/)<br/>**

2023-12-28 06:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/5/console)**

2023-12-28 06:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/5/)<br/>**

2024-01-02 05:23 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/7/console)**

2024-01-02 05:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/7/console)**

2024-01-02 05:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/7/)<br/>**

2024-01-02 08:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/8/console)**

2024-01-02 08:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/8/)<br/>**

2024-01-02 18:43 UTC, MathanKumarVaradhaRajaPerumal requested changes

2024-01-02 18:43 UTC, MathanKumarVaradhaRajaPerumal commented on File-Formats/DocIO/Working-with-LaTeX.md
> +document.LastParagraph.AppendMath(@"\overline{a}");
Why the same changes not done for Windows specific and vb

2024-01-02 18:43 UTC, MathanKumarVaradhaRajaPerumal commented on File-Formats/DocIO/Working-with-LaTeX.md
> +<td>@"\sqrt{a}"</td>
Whether the @ symbol is mandatory?

2024-01-02 18:43 UTC, MathanKumarVaradhaRajaPerumal commented on File-Formats/DocIO/Working-with-LaTeX.md
> +document.LastParagraph.AppendMath(@"{_{40}^{20}}100");
Add curly braces for 100 too

2024-01-02 18:43 UTC, MathanKumarVaradhaRajaPerumal commented on File-Formats/DocIO/Working-with-LaTeX.md
> +document.LastParagraph.AppendMath(@"{100}_{40}^{20}")
Why the same changes not done for Windows specific and vb

2024-01-03 05:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/11/console)**

2024-01-03 05:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/11/)<br/>**

2024-01-03 05:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/12/console)**

2024-01-03 05:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/12/)<br/>**

2024-01-03 05:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/fileformat-docs/13/console)**

2024-01-03 05:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-861360-Modify-LaTeX](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/13/)<br/>**

2024-01-03 07:06 UTC, MathanKumarVaradhaRajaPerumal approved these changes

2024-01-03 07:13 UTC, MohanaselvamJothi approved these changes

2024-01-03 07:14 UTC, merged