866304: Removed the WebKit Html to PDF related UG documentations.
syncfusion-content/fileformat-docs pull request #1794
Opened 2024-01-24 09:25 UTC by Sri-hari-haran-g

2024-01-24 09:26 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [866304](https://ci.syncfusion.com/job/Content/job/fileformat-docs/91/console)**

2024-01-24 09:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [866304](https://ci.syncfusion.com/job/Content/job/fileformat-docs/91/console)**

2024-01-24 10:42 UTC, chinnumuniyappan approved these changes

2024-01-24 10:57 UTC, sivaramgunabalan requested changes

2024-01-24 10:57 UTC, sivaramgunabalan commented on File-Formats/PDF/Converting-HTML-to-PDF.md
> +description: Learn how to convert HTML to PDF using 3 different rendering engines (Blink and IE) with various features like TOC, partial web page to PDF etc.
@Sri-hari-haran-g Need to change **3** different rendering engines to **2** different rendering engines

2024-01-24 11:04 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [866304](https://ci.syncfusion.com/job/Content/job/fileformat-docs/93/console)**

2024-01-24 11:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [866304](https://ci.syncfusion.com/job/Content/job/fileformat-docs/93/console)**

2024-01-24 11:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [866304](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/93/)<br/>**

2024-01-25 05:33 UTC, sivaramgunabalan approved these changes

2024-01-25 10:31 UTC, chinnumuniyappan approved these changes

2024-01-25 10:31 UTC, merged