ES-864081  Crop image in Presentation
syncfusion-content/fileformat-docs pull request #1884
Opened 2024-02-22 11:06 UTC by Venkateshmuruganandam

Hi All,
UG draft work for completed for Crop picture in presentation

Regards
Venkatesh

2024-02-22 11:07 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-864081-Crop-Picture](https://ci.syncfusion.com/job/Content/job/fileformat-docs/202/console)**

2024-02-22 11:14 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/fileformat-docs/202/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-02-22 11:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-864081-Crop-Picture](https://ci.syncfusion.com/job/Content/job/fileformat-docs/202/console)**

2024-02-22 11:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-864081-Crop-Picture](https://ci.syncfusion.com/job/Content/job/fileformat-docs/203/console)**

2024-02-22 11:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-864081-Crop-Picture](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/202/)<br/>**

2024-02-22 11:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-864081-Crop-Picture](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/203/)<br/>**

2024-02-26 12:00 UTC, MohanaselvamJothi requested changes

2024-02-26 12:12 UTC, MohanaselvamJothi requested changes

2024-02-26 12:12 UTC, MohanaselvamJothi commented on File-Formats/Presentation/Working-with-images.md
> +Refine the image dimensions by cropping out any unintended elements, using a cropping tool to focus the image on relevant areas.
Crop the images in an existing presentation or insert the cropped picture while creating a presentation from scratch by applying crop properties using the .NET PowerPoint Library.

2024-02-27 06:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-864081-Crop-Picture](https://ci.syncfusion.com/job/Content/job/fileformat-docs/210/console)**

2024-02-27 06:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-864081-Crop-Picture](https://ci.syncfusion.com/job/Content/job/FileFormat-docs/210/)<br/>**

2024-02-27 12:03 UTC, Chrispineagunja reviewed
This content is fine

2024-02-29 06:50 UTC, MohanaselvamJothi approved these changes

2024-02-29 06:50 UTC, merged