ES-865474-Add information about include \c switch in TOC and update - for figures, tables, and more in UG
syncfusion-content/fileformat-docs pull request #1913
Opened 2024-03-05 05:43 UTC by Venkateshmuruganandam

HI All,
Ug draft work completed.

Taks Link : <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/865474">Add information about include \c switch in TOC and update - for figures, tables, and more in UG </a>

Regards
venkatesh

2024-03-05 05:44 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/console)**

2024-03-05 05:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/console)**

2024-03-05 05:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/18/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-05 06:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/console)**

2024-03-05 06:49 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/artifact/cireports/)<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/)<br/>Image Alt Text Error(s): [1](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/19/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-05 07:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/20/console)**

2024-03-06 06:43 UTC, MathanKumarVaradhaRajaPerumal approved these changes

2024-03-06 08:41 UTC, MathanKumarVaradhaRajaPerumal requested changes

2024-03-06 08:41 UTC, MathanKumarVaradhaRajaPerumal commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +The following code example illustrates how to set the name of the sequence identifier employed in the creation of a table of figures using TableOfFiguresLabel API.
The following code example shows how to add a table of figures in Word document using TableOfFiguresLabel API.

2024-03-06 08:41 UTC, MathanKumarVaradhaRajaPerumal commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +The following code example illustrates how to exclude the caption's label and number in TOC entries during the creation of a table of figures using the IncludeCaptionLabelsAndNumbers API.
The following code example shows how to add a table of figures by exclude the caption's label and number in Word document using IncludeCaptionLabelsAndNumbers API.

2024-03-06 08:44 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/32/console)**

2024-03-06 08:44 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/fileformat-docs/32/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-06 08:45 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/32/)<br/>**

2024-03-06 08:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/console)**

2024-03-06 08:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/33/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-06 13:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/36/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/36/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/36/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/36/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/36/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/36/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/36/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/36/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/36/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-06 13:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/console)**

2024-03-06 13:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/37/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-06 13:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/console)**

2024-03-06 13:52 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/artifact/cireports/)<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/38/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-07 07:01 UTC, MohanaselvamJothi approved these changes

2024-03-07 07:33 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/fileformat-docs/39/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-07 07:33 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/39/)<br/>**

2024-03-07 07:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/console)**

2024-03-07 07:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-865474-TableofFigures](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/41/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-07 09:08 UTC, MohanaselvamJothi approved these changes

2024-03-07 09:49 UTC, MohanaselvamJothi approved these changes

2024-03-07 09:49 UTC, merged