SEO-180837-File-Formats-Redirection
syncfusion-content/fileformat-docs pull request #1941
Opened 2024-03-13 11:23 UTC by Scholar-jaruha

Hi @Aishwarya-Ganesan,
I have worked on changing redirection links, please review.
Regards,
Scholar.

2024-03-13 11:24 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/console)**

2024-03-13 11:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/console)**

2024-03-13 11:32 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/artifact/cireports/)<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/73/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 05:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/console)**

2024-03-14 05:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/82/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 09:09 UTC, Yvone-Atieno requested changes
Commented

2024-03-14 09:14 UTC, Scholar-jaruha commented on File-Formats/PDF/Convert-HTML-To-PDF/Convert-HTML-to-PDF-in-AWS-Lambda.md
> +description: Learn how to convert HTML to PDF in AWS Lambda using Syncfusion .NET HTML converter library.
done

2024-03-14 09:17 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/artifact/cireports/)<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/94/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 09:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/console)**

2024-03-14 09:22 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/artifact/cireports/)<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/95/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 09:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/console)**

2024-03-14 09:25 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-180837-File-Formats-Redirection](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/96/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 09:29 UTC, Yvone-Atieno approved these changes
Approved

2024-03-14 12:59 UTC, Aishwarya-Ganesan approved these changes

2024-03-14 12:59 UTC, merged