SEO-2008_Site_Audit_Issues
syncfusion-content/fileformat-docs pull request #198
Opened 2022-03-07 09:41 UTC by gowthamanthavasiyappan

Hi @ChristoIssac,

Worked on Duplicate Title Tags in Alexa, merge these changes.

Regards,
Gowthaman

2022-03-07 09:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/328/console)**

2022-03-07 09:43 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/328/artifact/cireports/)<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/328/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/328/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/328/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/328/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/328/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/328/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/328/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-07 09:51 UTC, gowthamanthavasiyappan commented
rebuild

2022-03-07 09:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/329/console)**

2022-03-07 09:53 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/329/artifact/cireports/)<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/329/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/329/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/329/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/329/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/329/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/329/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/329/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-07 10:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/330/console)**

2022-03-08 13:44 UTC, ChristoIssac requested changes

2022-03-16 11:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/421/console)**

2022-03-16 12:00 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/421/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/421/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/421/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/421/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/421/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/421/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/421/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-16 12:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/422/console)**

2022-03-16 12:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/422/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/422/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/422/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/422/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/422/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/422/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/422/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-16 12:09 UTC, ChristoIssac requested changes

2022-03-16 12:09 UTC, ChristoIssac commented on File-Formats/DocIO/Working-with-Bookmarks.md
> +title: Working with Bookmarks in File Formats Word Library | Syncfusion
Don't use file formats hereafter. use `Document processing Word Library` instead

2022-03-16 12:16 UTC, gowthamanthavasiyappan commented on File-Formats/DocIO/Working-with-Bookmarks.md
> +title: Working with Bookmarks in File Formats Word Library | Syncfusion
Used Document processing instead File Formats

2022-03-16 12:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/423/console)**

2022-03-16 12:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-1937_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/423/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/423/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/423/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/423/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/423/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/423/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/423/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-01 07:03 UTC, ChristoIssac approved these changes

2022-05-05 09:14 UTC, closed without merging