SEO-187032-File-Formats-H1-Tag-Missing
syncfusion-content/fileformat-docs pull request #2160
Opened 2024-08-05 12:02 UTC by EsterAtieno

Hi @Yvone-Atieno ,
Have made changes,Kindly review.

Title | Description
-- | --
Task Category | Site Audit
Content Task Link/Mail Screenshot | NA
Hotfix | #4375
Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187032/
Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B2898E97F-22C5-48F0-B677-88AB8168596C%7D&file=Ester.xlsx&action=default&mobileredirect=true

Changes Made | Reason for change | Reason for not identifying earlier
-- | -- | --
Redirect link | To improve accessibility |  

Regards,
Ester

2024-08-05 12:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187032-File-Formats-H1-Tag-Missing](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/console)**

2024-08-05 12:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187032-File-Formats-H1-Tag-Missing](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/310/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-05 15:22 UTC, Yvone-Atieno requested changes
Commented

2024-08-05 15:22 UTC, Yvone-Atieno commented on File-Formats/PDF/Working-with-PDF-Templates.md
> +# Working with PDF Templates in .NET PDF
Don't add PDF

2024-08-06 05:47 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-187032-File-Formats-H1-Tag-Missing](https://ci.syncfusion.com/job/Content/job/fileformat-docs/316/console)**

2024-08-06 05:51 UTC, EsterAtieno commented on File-Formats/PDF/Working-with-PDF-Templates.md
> +# Working with PDF Templates in .NET PDF
resolved

2024-08-06 05:58 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [SEO-187032-File-Formats-H1-Tag-Missing](https://ci.syncfusion.com/job/Content/job/fileformat-docs/316/)<br/>**

2024-08-06 06:01 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-187032-File-Formats-H1-Tag-Missing](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/console)**

2024-08-06 06:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187032-File-Formats-H1-Tag-Missing](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/console)**

2024-08-06 06:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187032-File-Formats-H1-Tag-Missing](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/fileformat-docs/317/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-06 07:03 UTC, Yvone-Atieno approved these changes
Approved

2024-08-14 12:30 UTC, closed without merging