WF-51781-Added more use cases of find and replace in UG documentation
syncfusion-content/fileformat-docs pull request #523
Opened 2022-09-14 12:18 UTC by Suriya-Balamurugan

Kindly review the below merge request and let me know your feedback.

<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-51781">https://syncfusion.atlassian.net/browse/WF-51781</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Added more use cases of find and replace in UG documentation
</td>
</tr>
<tr>
<td>
Changes Done
</td>
<td>
Added UG documentation for 6 API's in find and replace functionality.<p/>

- Replace(Regex pattern, string replace);
- ReplaceSingleLine(Regex pattern, string replace);
- Find(Regex pattern);
- Replace(string given, TextSelection textSelection, bool caseSensitive, bool wholeWord, bool saveFormatting);
- FindSingleLine(Regex pattern);
- ReplaceSingleLine(Regex pattern, TextSelection replacement);

</td>
</tr>
<tr>
<td>
Content Review Confirmation
</td>
<td>
Yes - 
<a href="https://syncfusion.atlassian.net/browse/DOC-4679">https://syncfusion.atlassian.net/browse/DOC-4679</a>
</td>
</tr>
<tr>
<td>
GitHub Samples Pull Request
</td>
<td>
https://github.com/SyncfusionExamples/DocIO-Examples/pull/25
</td>
</tr>
</table>

2022-09-14 12:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-51781](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/856/console)**

2022-09-14 12:19 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/856/artifact/cireports/)<br/>Build Location: [WF-51781](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/856/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/856/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/856/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/856/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/856/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [4](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/856/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/856/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-14 17:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-51781](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/858/console)**

2022-09-14 17:37 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/858/artifact/cireports/)<br/>Build Location: [WF-51781](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/858/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/858/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/858/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/858/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/858/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [4](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/858/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/858/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-15 06:06 UTC, MohanaselvamJothi requested changes

2022-09-15 06:49 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/Working-with-Find-and-Replace.md
> +You can select a text using the `Find` method and replace text in a Word document with that selected text and formatting (bold, italic, and so on).
Addressed

2022-09-15 06:51 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/Working-with-Find-and-Replace.md
> +## Find and Replace the pattern of text with normal text
Addressed

2022-09-15 06:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-51781](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/862/console)**

2022-09-15 06:53 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/862/artifact/cireports/)<br/>Build Location: [WF-51781](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/862/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/862/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/862/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/862/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/862/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [4](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/862/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/862/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-15 07:09 UTC, Suriya-Balamurugan commented
rebuild

2022-09-15 07:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-51781](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/863/console)**

2022-09-15 07:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-51781](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/863/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/863/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/863/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/863/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/863/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/863/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/fileformat-docs/863/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-15 07:19 UTC, MohanaselvamJothi approved these changes

2022-09-15 07:19 UTC, merged