WF-64587-Add information about export chart in the Word document as image
syncfusion-content/fileformat-docs pull request #605
Opened 2022-10-20 04:44 UTC by AntonihilSahayaraj

Add information about export chart in the Word document as image

2022-10-20 04:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/810/console)**

2022-10-20 04:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/810/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/810/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/810/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/810/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/810/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/810/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/810/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-20 04:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/811/console)**

2022-10-20 04:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/811/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/811/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/811/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/811/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/811/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/811/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/811/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-28 08:04 UTC, MohanaselvamJothi requested changes

2022-10-28 08:04 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Charts.md
> +using (Stream docStream = typeof(App).GetTypeInfo().Assembly.GetManifestResourceStream("Sample.Assets.Template.docx"))
//DocIO supports chart to image conversion in Windows Forms, WPF, ASP.NET and ASP.NET MVC platform alone. You can convert chart as image in UWP using DocIORenderer.

2022-10-28 08:04 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Charts.md
> +            //Get the chart element from paragraph.
Move this line before DocIORenderer

2022-10-28 08:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/817/console)**

2022-10-28 08:38 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins-ci.syncfusion.com:8443/job/Content/job/fileformat-docs/817/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2022-10-28 08:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/818/console)**

2022-10-28 08:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/818/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/818/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/818/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/818/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/818/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/818/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/818/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-28 08:41 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins-ci.syncfusion.com:8443/job/Content/job/fileformat-docs/819/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2022-10-28 08:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/820/console)**

2022-10-28 08:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/820/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/820/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/820/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/820/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/820/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/820/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/820/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-28 09:00 UTC, MohanaselvamJothi approved these changes

2022-11-07 12:27 UTC, Joshuaotieno commented on File-Formats/DocIO/Working-with-Charts.md
> +        //Get the first paragraph from section.
//Get the first paragraph from the section.

2022-11-09 04:48 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/832/console)**

2022-11-09 04:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/832/console)**

2022-11-09 05:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/832/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/832/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/832/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/832/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/832/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/832/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/fileformat-docs/832/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-10 12:21 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/816/console)**

2022-11-10 12:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/816/console)**

2022-11-10 12:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64587-Add_information_about_export_chart_in_the_Word_document_as_image](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/816/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/816/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/816/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/816/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/816/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/816/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/816/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-29 04:56 UTC, MohanaselvamJothi approved these changes

2022-11-29 04:56 UTC, merged