WF-64807-Adding UG documentation to IncludeNewLineCharacters API
syncfusion-content/fileformat-docs pull request #670
Opened 2022-11-30 11:32 UTC by chrispojunior

<table style="width: 521.306px;">
<tbody>
<tr>
<td style="width: 156px;">Task Link</td>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-64807</td>
</tr>
<tr>
<td style="width: 156px;">Description</td>
<td style="width: 349.306px;">Add UG document to&nbsp; customize Table of contents</td>
</tr>
<tr>
<td style="width: 156px;">Solution</td>
<td style="width: 349.306px;">Added code snippet to customize table of contents</td>
</tr>
<tr>
<td style="width: 156px;">Content review confirmation</td>
<td style="width: 349.306px;">Not yet</td>
</tr>
</tbody>
</table>

2022-11-30 11:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/924/console)**

2022-12-02 08:19 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/930/console)**

2022-12-02 08:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/930/console)**

2022-12-02 08:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/930/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/930/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/930/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/930/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/930/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/930/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/930/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-02 08:32 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/931/artifact/cireports/)<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/931/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/931/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/931/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/931/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/931/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/931/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/fileformat-docs/931/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-02 08:41 UTC, MohanaselvamJothi requested changes

2022-12-05 06:20 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/932/console)**

2022-12-05 06:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/932/console)**

2022-12-06 09:35 UTC, MohanaselvamJothi requested changes

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    // Append table of content to the end of the paragraph with the specified lower and upper heading levels.
//Appends the TOC field with LowerHeadingLevel and UpperHeadingLevel to determines the TOC entries

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    TableOfContent tableOfContent = paragraph.AppendTOC(2, 5);
paragraph.AppendTOC(1, 3);

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    //Set starting heading level of the table of contents.
//Set lower heading level for TOC

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    //Set ending heading level of the table of contents.
//Set upper heading level for TOC.

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    //Use default heading styles
//Enable a flag to use default heading styles in TOC entries.

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    //Show page numbers in table of content.
//Enable a flag to show page numbers in TOC entries.

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    //Set page numbers to right alignment.
//Disable a flag to align page numbers after to the TOC entries.

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    //Set hyperlinks for the TOC levels.
//Disable a flag to preserve TOC entries without hyperlinks

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    //Include new line to preserve newline characters TableOfContent.
//Enable a flag to include new line characters in TOC entries.

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    tableOfContent.UseOutlineLevels = true;
//Enable a flag to consider outline level paragraphs in TOC entries.

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +    tableOfContent.UseTableEntryFields = true;
//Enable a flag to use table entry fields in TOC entries

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +Switches are used to change the default settings in word document. TOC will determine the TOC entries based on the TOC switches. You can set heading levels, specify whether to use default heading sty
You can modify the preservation of TOC entries in Word document by applying switches to table of contents. You can apply switches to preserve TOC entries as hyperlink or not, use default heading styles, preserve page numbers or not, aligning the page numbers, preserve new line characters, preserve outline level paragraphs, and preserve table of entry fields in the TOC entries using Word (DocIO) library.

2022-12-06 09:35 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +## Applying switches for table of contents
Apply switches for table of contents

2022-12-06 12:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/941/console)**

2022-12-06 12:01 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/941/artifact/cireports/)<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/941/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/941/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/941/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/941/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/941/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/941/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/fileformat-docs/941/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-06 12:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/942/console)**

2022-12-06 12:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/942/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/942/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/942/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/942/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/942/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/942/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/942/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-07 09:24 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +You can modify the preservation of TOC entries in Word document by applying switches to table of contents. You can apply switches to preserve TOC entries as hyperlink or not, use default heading styl
You can modify the preservation of TOC entries in a Word document by applying switches to the table of contents, and you can also apply switches to preserve TOC entries as hyperlinks or not, use the default heading styles, preserve page numbers or not, align the page numbers, preserve new line characters, preserve outline level paragraphs, and preserve table of entry fields in the TOC entries using Word (DocIO) library.

2022-12-07 09:24 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +The following code example illustrates how to apply switches for table of contents.
The following code example illustrates how to apply switches for the table of contents.

2022-12-07 09:25 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Add a section into the Word document.
Add a section to the Word document.

2022-12-07 09:25 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Add a paragraph into the created section.
Add a paragraph to the created section.

2022-12-07 09:26 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Append the TOC field with LowerHeadingLevel and UpperHeadingLevel to determines the TOC entries.
Append the TOC field with LowerHeadingLevel and UpperHeadingLevel to determine the TOC entries.

2022-12-07 09:27 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Disable a flag to align page numbers after to the TOC entries.
Disable a flag to align page numbers after the TOC entries.

2022-12-07 09:27 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Add a paragraph into the section.
Add a paragraph to the section.

2022-12-07 09:45 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Add a section into the Word document.
Add a section to the Word document.

2022-12-07 09:46 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Sets a built-in heading style.
Set a built-in heading style.

2022-12-07 09:47 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Add a section into the Word document.
Add a section to the Word document.

2022-12-07 09:48 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Add the text into the new paragraph of the section.
Add the text to the new paragraph of the section.

2022-12-07 09:51 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Add a section into the Word document.
Add a section to the Word document

2022-12-07 09:51 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Update the table of content.
Update the table of contents.

2022-12-07 09:52 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//DocIO supports Table of contents in WPF, Windows Forms platforms alone
Keep full stop at the end

2022-12-07 10:13 UTC, laksmipriyamurugesan commented
Reviewed the PR.

2022-12-07 10:15 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Please download the helper files from the below link to save the stream as file and open the file for viewing in Xamarin platform
Please download the helper files from the following link to save the stream as a file and open the file for viewing on Xamarin platform.

Keep full stop at the end.

2022-12-07 10:15 UTC, laksmipriyamurugesan commented on File-Formats/DocIO/Working-with-Table-Of-Contents.md
> +//Enable a flag to consider outline level paragraphs in TOC entries.
Enable a flag to consider outline-level paragraphs in TOC entries.

2022-12-07 11:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/947/console)**

2022-12-07 11:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/947/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/947/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/947/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/947/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/947/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/947/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/947/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-07 12:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64807-Add-UG-document-to-IncludeNewLineCharacters-API](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/949/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/949/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/949/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/949/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/949/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/949/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/949/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-07 12:52 UTC, MohanaselvamJothi approved these changes

2022-12-07 12:52 UTC, merged