WF-65009-Add hyperlink for the APIs in DocIO UG
syncfusion-content/fileformat-docs pull request #730
Opened 2022-12-21 08:20 UTC by sharonaumao

<table style="width: 521.306px;">
<tbody>
<tr>
<td style="width: 156px;">Task Link</td>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-65009</td>
</tr>
<tr>
<td style="width: 156px;">Description</td>
<td style="width: 349.306px;">Resolved formatting issues in Presentation UG</td>
</tr>
<tr>
<td style="width: 156px;">Solution</td>
<td style="width: 349.306px;">add hyperlink to APIs in Getting started</td>
</tr>
<tr>
<td style="width: 156px;">Content review confirmation</td>
<td style="width: 349.306px;">Yes</td>
</tr>
</tbody>
</table>

2022-12-21 08:21 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1023/console)**

2022-12-21 08:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1023/console)**

2022-12-21 08:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1023/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1023/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1023/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1023/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1023/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1023/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1023/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-21 13:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1026/console)**

2022-12-21 13:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1026/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1026/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1026/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1026/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1026/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1026/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1026/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-22 08:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1037/console)**

2022-12-22 08:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1037/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1037/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1037/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1037/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1037/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1037/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1037/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-23 05:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1045/console)**

2022-12-23 05:15 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1045/artifact/cireports/)<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1045/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1045/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1045/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1045/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1045/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [5](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1045/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/fileformat-docs/1045/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-23 07:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1049/console)**

2022-12-23 07:33 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1049/artifact/cireports/)<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1049/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1049/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1049/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1049/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1049/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [5](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1049/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/fileformat-docs/1049/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-27 16:08 UTC, Suriya-Balamurugan requested changes

2022-12-28 05:25 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1066/console)**

2022-12-28 05:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1066/console)**

2022-12-28 05:26 UTC, sharonaumao commented on File-Formats/DocIO/Accepting-or-Rejecting-Track-Changes.md
> +You can **accept all track changes in Word document** using [AcceptAll](https://help.syncfusion.com/cr/file-formats/Syncfusion.DocIO.DLS.RevisionCollection.html#Syncfusion_DocIO_DLS_RevisionCollectio
@Suriya-Balamurugan - the feedback is addressed

2022-12-28 05:26 UTC, sharonaumao commented on File-Formats/DocIO/Loading-and-Saving-document.md
> +You can open an existing document from stream by using either the overloads of [Open](https://help.syncfusion.com/cr/file-formats/Syncfusion.DocIO.DLS.WordDocument.html#Syncfusion_DocIO_DLS_WordDocum
@Suriya-Balamurugan -the feedback is addressed

2022-12-28 05:27 UTC, sharonaumao commented on File-Formats/DocIO/Loading-and-Saving-document.md
> +You can open an existing Word document by using either the [Open](https://help.syncfusion.com/cr/file-formats/Syncfusion.DocIO.DLS.WordDocument.html#Syncfusion_DocIO_DLS_WordDocument_Open_System_Stri
@Suriya-Balamurugan -the feedback is addressed

2022-12-28 05:27 UTC, sharonaumao commented on File-Formats/DocIO/Working-with-Paragraph.md
> +* Chart: Represented by an instance of [WChart[(https://help.syncfusion.com/cr/file-formats/Syncfusion.DocIO.DLS.WChart.html).
@Suriya-Balamurugan - the feedback is addressed

2022-12-28 06:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1067/console)**

2022-12-28 06:29 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1067/artifact/cireports/)<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1067/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1067/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1067/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1067/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1067/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [5](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1067/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/fileformat-docs/1067/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-28 06:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1068/console)**

2022-12-28 06:52 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1068/artifact/cireports/)<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1068/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1068/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1068/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1068/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1068/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [5](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1068/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/fileformat-docs/1068/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-28 07:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1070/console)**

2022-12-28 07:16 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1070/artifact/cireports/)<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1070/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1070/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1070/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1070/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1070/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [3](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1070/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/fileformat-docs/1070/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-28 07:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1071/console)**

2022-12-28 07:38 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1071/artifact/cireports/)<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1071/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1071/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1071/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1071/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1071/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [3](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1071/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/fileformat-docs/1071/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-28 07:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1072/console)**

2022-12-28 08:00 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65009-Add-Hyperlink](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1072/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1072/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1072/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1072/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1072/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1072/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1072/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-28 08:01 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2022-12-28 08:01 UTC, merged