WF-65091-Fix recurring formatting issues
syncfusion-content/fileformat-docs pull request #785
Opened 2023-01-05 14:01 UTC by sharonaumao

<table style="width: 521.306px;">
<tbody>
<tr>
<td style="width: 156px;">Task Link</td>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-65091</td>
</tr>
<tr>
<td style="width: 156px;">Description</td>
<td style="width: 349.306px;">Resolved formatting issues in Presentation UG</td>
</tr>
<tr>
<td style="width: 156px;">Solution</td>
<td style="width: 349.306px;">Resolve formatting and hyperlink issues in FAQ, Getting-Started, html, word-to-image, word-to-pdf</td>
</tr>
<tr>
<td style="width: 156px;">Content review confirmation</td>
<td style="width: 349.306px;">Yes</td>
</tr>
</tbody>
</table>

[WF-65091]: https://syncfusion.atlassian.net/browse/WF-65091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-01-05 14:02 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1150/console)**

2023-01-05 14:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1150/console)**

2023-01-05 14:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1150/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1150/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1150/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1150/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1150/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1150/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1150/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-06 09:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1152/console)**

2023-01-06 09:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1152/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1152/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1152/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1152/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1152/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1152/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1152/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-06 09:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1153/console)**

2023-01-06 09:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1153/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1153/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1153/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1153/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1153/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1153/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1153/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-06 11:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1154/console)**

2023-01-06 11:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1154/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1154/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1154/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1154/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1154/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1154/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1154/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-09 08:05 UTC, Suriya-Balamurugan requested changes

2023-01-09 08:56 UTC, sharonaumao commented on File-Formats/DocIO/Working-with-Bookmarks.md
> +
@Suriya-Balamurugan -The empty line is removed

2023-01-09 08:56 UTC, sharonaumao commented on File-Formats/DocIO/Working-with-Tables.md
> +The following code example illustrates how to load an existing document and apply table formatting options such as [Borders](https://help.syncfusion.com/cr/file-formats/Syncfusion.DocIO.DLS.RowFormat
@Suriya-Balamurugan -Addressed

2023-01-09 08:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1160/console)**

2023-01-09 08:56 UTC, sharonaumao commented on File-Formats/DocIO/mail-merge/mail-merge-events.md
> +The following code example shows how to bind the image from file system during Mail merge process by using [MergeImageFieldEventHandler](https://help.syncfusion.com/cr/file-formats/Syncfusion.DocIO.D
@Suriya-Balamurugan -Feedback addressed

2023-01-09 08:57 UTC, sharonaumao commented on File-Formats/DocIO/mail-merge/mail-merge-for-group.md
> +  1.*TableStart* and *TableEnd* region is preferred for performing Mail merge inside the table cell.
@Suriya-Balamurugan -Feedback addressed

2023-01-09 08:57 UTC, sharonaumao commented on File-Formats/DocIO/word-file-formats.md
@Suriya-Balamurugan -Feedback addressed

2023-01-09 08:57 UTC, sharonaumao commented on File-Formats/DocIO/word-to-pdf.md
> +
@Suriya-Balamurugan -Feedback addressed

2023-01-09 08:57 UTC, sharonaumao commented on File-Formats/Presentation/Loading-and-Saving-the-Presentation.md
> +You can open an existing PowerPoint Presentation from stream by using the overloads of [Open](https://help.syncfusion.com/cr/file-formats/Syncfusion.Presentation.Presentation.html#Syncfusion_Presenta
@Suriya-Balamurugan -Feedback addressed

2023-01-09 08:58 UTC, sharonaumao commented on File-Formats/Presentation/NuGet-Packages-Required.md
> +
@Suriya-Balamurugan -Feedback addressed

2023-01-09 08:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65091-Fix-Formatting-issues](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1160/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1160/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1160/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1160/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1160/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1160/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1160/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-09 09:52 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-01-09 09:53 UTC, MohanaselvamJothi approved these changes

2023-01-09 09:54 UTC, merged