WF-64420 Adding mail merge KB links to UG
syncfusion-content/fileformat-docs pull request #826
Opened 2023-01-23 13:39 UTC by elizabethatienoo

<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/EJ2CORE-1025">https://syncfusion.atlassian.net/browse/EJ2CORE-1025</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add mail merge KB Link to UG
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added mail merge KB Links to UG
</td>
</tr>
<tr>
<td>
Content review confirmation
</td>
<td>
 Done
</td>
</tr>
</table>

2023-01-23 13:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1216/console)**

2023-01-23 13:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1216/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1216/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1216/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1216/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1216/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1216/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1216/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-01 14:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1231/console)**

2023-02-01 14:24 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1231/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-02-01 14:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1232/console)**

2023-02-01 14:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1232/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1232/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1232/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1232/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1232/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1232/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1232/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-02 06:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1233/console)**

2023-02-02 06:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1233/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1233/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1233/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1233/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1233/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1233/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1233/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-02 06:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1234/console)**

2023-02-02 06:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1234/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1234/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1234/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1234/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1234/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1234/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1234/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-02 06:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1235/console)**

2023-02-02 06:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1235/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1235/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1235/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1235/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1235/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1235/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1235/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-02 07:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1236/console)**

2023-02-02 07:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1236/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1236/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1236/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1236/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1236/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1236/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1236/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-02 09:03 UTC, Suriya-Balamurugan requested changes

2023-02-02 09:03 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/mail-merge/simple-mail-merge.md
> +<td style="width: 182.986px;"><strong>Execute Method </strong></td>
Change heading "Execute Method" as "Overloads"

2023-02-02 09:03 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/mail-merge/mail-merge-for-nested-groups.md
> +## See Also
Separate the overloads in each page

2023-02-02 09:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1237/console)**

2023-02-02 09:11 UTC, elizabethatienoo commented on File-Formats/DocIO/mail-merge/simple-mail-merge.md
> +<td style="width: 182.986px;"><strong>Execute Method </strong></td>
Addressed

2023-02-02 09:11 UTC, elizabethatienoo commented on File-Formats/DocIO/mail-merge/mail-merge-for-nested-groups.md
> +## See Also
Addressed

2023-02-02 09:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1237/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1237/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1237/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1237/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1237/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1237/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1237/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-02 09:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1238/console)**

2023-02-02 09:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1238/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1238/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1238/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1238/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1238/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1238/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1238/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-02 12:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-64420-Add-mail-merge-KB-links-in-UG](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1239/console)**

2023-02-03 04:37 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-02-03 04:39 UTC, MohanaselvamJothi approved these changes

2023-02-03 04:39 UTC, merged