WF-65375-Add information about HTML export option
syncfusion-content/fileformat-docs pull request #861
Opened 2023-02-09 11:52 UTC by sharonaumao

<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65424">https://syncfusion.atlassian.net/browse/WF-65424</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add information about HTML export option
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Add information about HTML export option
</td>
</tr>
<tr>
<td>
Content review confirmation
</td>
<td>
 Done
</td>
</tr>
</table>

2023-02-09 11:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65375-UGLINKS](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1255/console)**

2023-02-09 11:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65375-UGLINKS](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1255/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1255/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1255/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1255/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1255/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1255/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1255/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-13 10:40 UTC, Suriya-Balamurugan requested changes

2023-02-13 10:40 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/html.md
Add about the API here

2023-02-13 12:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65375-UGLINKS](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1290/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1290/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1290/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1290/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1290/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1290/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1290/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-14 08:13 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-65375-UGLINKS](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1293/console)**

2023-02-14 08:13 UTC, sharonaumao commented on File-Formats/DocIO/html.md
@Suriya-Balamurugan -Addressed

2023-02-14 08:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65375-UGLINKS](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1293/console)**

2023-02-14 08:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65375-UGLINKS](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1293/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1293/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1293/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1293/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1293/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1293/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1293/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-14 13:12 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-02-15 05:40 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-02-15 06:00 UTC, MohanaselvamJothi approved these changes

2023-02-15 06:00 UTC, merged