WF-57277-Made UG changes to add missed statements
syncfusion-content/fileformat-docs pull request #864
Opened 2023-02-10 14:05 UTC by elizabethatienoo

<table style="width: 521.306px;">
<tbody>
<tr>
<td style="width: 156px;">Task Link</td>
<td style="width: 349.306px;">https://[syncfusion.atlassian.net/browse/WF-57277](https://syncfusion.atlassian.net/browse/WF-57277)</td>
</tr>
<tr>
<td style="width: 156px;">Description</td>
<td style="width: 349.306px;">Added Blazor Server side in Word to PDF namespace list in DocIO UG</td>
</tr>
<tr>
<td style="width: 156px;">Solution</td>
<td style="width: 349.306px;">Added Blazor Server side in Word to PDF namespace list, Added license clearance information to use Microsoft fonts, Added a note in UG about how to insert multiple body items using mergefield event handler</td>
</tr>
<tr>
<td style="width: 156px;">Content review confirmation</td>
<td style="width: 349.306px;">Yes</td>
</tr>
</tbody>
</table>

2023-02-10 14:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1278/console)**

2023-02-13 12:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/console)**

2023-02-13 12:37 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/artifact/cireports/)<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [2](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1291/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-13 14:37 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1292/artifact/cireports/)<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1292/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [2](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1292/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1292/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1292/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1292/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1292/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1292/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1292/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-14 13:32 UTC, Chrispineagunja commented on File-Formats/DocIO/FAQ.md
> +N> To use Microsoft fonts in your environment, kindly get license clearance from Microsoft at your side.
N> To use Microsoft fonts in your environment, kindly get the license clearance from Microsoft on your side.

2023-02-14 13:32 UTC, Chrispineagunja commented on File-Formats/DocIO/mail-merge/mail-merge-events.md
> +N> While executing mail merge, DocIO internally uses copy of particular region for populating the contents. Sometimes, it may rise unexcepted problems due to inserting multiple body items in to the r
N> While executing mail merge, DocIO internally uses a copy of a particular region for populating the contents. Sometimes, unexpected problems may arise due to inserting multiple body items into the region through the mail merge process. So, to insert multiple body items using the mergefield event handler, you are recommended to use this [approach](https://www.syncfusion.com/kb/11701/how-to-replace-merge-field-with-html-string-using-mail-merge) at your side.

2023-02-14 13:32 UTC, Chrispineagunja commented on File-Formats/DocIO/word-to-pdf.md
> -**For ASP.NET Core and Xamarin applications**
**For ASP.NET Core, Blazor, Xamarin, WinUI, and .NET MAUI applications**

2023-02-15 05:00 UTC, Suriya-Balamurugan requested changes

2023-02-15 05:00 UTC, Suriya-Balamurugan commented on File-Formats/DocIO/mail-merge/mail-merge-events.md
> +N> N> While executing mail merge, DocIO internally uses a copy of a particular region for populating the contents. Sometimes, unexpected problems may arise due to inserting multiple body items into t
You wrongly added two note. Please remove one N>

2023-02-15 05:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/console)**

2023-02-15 05:13 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/artifact/cireports/)<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1295/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-15 06:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1299/console)**

2023-02-15 06:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1299/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1299/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1299/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1299/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1299/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1299/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1299/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-20 08:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1320/console)**

2023-02-20 08:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1320/console)**

2023-02-20 08:45 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-57277-Add-Blazer-Server](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1320/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1320/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1320/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1320/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1320/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1320/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1320/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-20 09:25 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-02-20 10:14 UTC, MohanaselvamJothi approved these changes

2023-02-20 10:14 UTC, merged