WF-65244-UG documentation for Markdown to Word Conversion
syncfusion-content/fileformat-docs pull request #921
Opened 2023-03-03 08:57 UTC by sharonaumao

<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65244">https://syncfusion.atlassian.net/browse/WF-65244</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add UG document for Markdown to Word conversion
</td>
</tr>
<td>
Content review confirmation
</td>
<td>
 Not yet
</td>
</tr>
</table>

2023-03-03 08:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1366/console)**

2023-03-03 10:04 UTC, MohanaselvamJothi requested changes

2023-03-03 10:04 UTC, MohanaselvamJothi commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +        args.ImageStream = assembly.GetManifestResourceStream("Sample.Assets.Image_1.png");
Use the sample name 
"Customize_image.Assets.Image_1.png"

Address the same feedbacks for uwp, xamarin

2023-03-03 12:51 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/console)**

2023-03-03 13:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/console)**

2023-03-03 13:01 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/artifact/cireports/)<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [3](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1368/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +title: Convert Markdown to Word document in C# | DocIO | Syncfusion
Title: Convert Markdown to Word document in C# | DocIO | Syncfusion

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +description: Convert Markdown to Word document in C# using Syncfusion .NET Word (DocIO) library without Microsoft Word or interop dependencies
Description: Convert Markdown to Word document in C# using the Syncfusion .NET Word (DocIO) library without Microsoft Word or interop dependencies.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +platform: file-formats
Platform: File-formats

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +control: DocIO
Control: DocIO

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +documentation: UG
Documentation: UG

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +Markdown is a lightweight markup language that adds formatting elements to plain text documents. The .NET Word (DocIO) library supports to convert Markdown to Word document and vice versa, which most
Markdown is a lightweight markup language that adds formatting elements to plain text documents. The .NET Word (DocIO) library supports converting Markdown to Word document and vice versa, which mostly follows the CommonMark specification and GitHub-flavored syntax.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +Convert an existing markdown file to Word document (DOC, DOCX and RTF) using the .NET Word (DocIO) library.
Convert an existing markdown file to a Word document (DOC, DOCX, and RTF) using the .NET Word (DocIO) library.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +//Please refer to the following link to save the Word document in UWP platform
//Please refer to the following link to save a Word document in the UWP platform.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +        //Download the Word document in the browser.
//Download a Word document in the browser.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +T> You can also save the markdown file as [HTML](https://help.syncfusion.com/file-formats/docio/html), [PDF](https://help.syncfusion.com/file-formats/docio/word-to-pdf) and [Image](https://help.syncf
T> You can also save the markdown file as [HTML](https://help.syncfusion.com/file-formats/docio/html), [PDF](https://help.syncfusion.com/file-formats/docio/word-to-pdf), and [Image](https://help.syncfusion.com/file-formats/docio/word-to-image).

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +The .NET Word (DocIO) library provides an MdImageNodeVisited event, which is used to customize image data while importing Markdown file. You can implement the logic to customize the image data by usi
The .NET Word (DocIO) library provides a MdImageNodeVisited event, which customizes image data while importing a Markdown file. Implement the logic to customize the image data by using this MdImageNodeVisited event.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +The following code example shows how to load image data based on image source path when importing the Markdown files.
The following code example shows how to load the image data based on the image source path when importing the Markdown files.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +    //Save the stream as a Word document in local machine.
//Save the stream as a Word document in the local machine.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +    //Please refer to the following link to save the Word document in UWP platform
//Please refer to the following link to save a Word document in the UWP platform.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +    //Please download the helper files from the following link to save the stream as a file and open the file for viewing in Xamarin platform
//Please download the helper files from the following link to save the stream as a file and open the file for viewing in the Xamarin platform.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +The following code examples show the event handler to customize the image based on source path.
The following code examples show the event handler to customize the image based on the source path.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +    'Retrive the image from website and use it.
'Retrieve the image from the website and use it.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +    //Retrive the image from the website and use it.
//Retrieve the image from the website and use it.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +    //Retrive the image from the website and use it.
//Retrieve the image from the website and use it.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +    //Retrive the image from the website and use it.
//Retrieve the image from the website and use it.

2023-03-07 05:38 UTC, Chrispineagunja commented on File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
> +N> Hook the event handler before opening Word document as per above code example.
N> Hook the event handler before opening a Word document as per the above code example.

2023-03-07 09:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/console)**

2023-03-07 09:46 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/artifact/cireports/)<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [3](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1379/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-09 05:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/console)**

2023-03-09 05:49 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/artifact/cireports/)<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [3](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1389/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-09 06:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1390/console)**

2023-03-09 06:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65244-UG-for-Markdown-to-Word-Conversion](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1390/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1390/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1390/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1390/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1390/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1390/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1390/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-09 06:51 UTC, merged