WF-65756-Adding Opening and Saving in DocIO
syncfusion-content/fileformat-docs pull request #963
Opened 2023-03-21 11:15 UTC by sharonaumao

<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65756">https://syncfusion.atlassian.net/browse/WF-65756</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add open and save codes of MVC platform
</td>
</tr>
<td>
Content review confirmation
</td>
<td>
 Not yet
</td>
</tr>
</table>

2023-03-21 11:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1428/)<br/>**

2023-03-21 11:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1429/)<br/>**

2023-03-22 05:31 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1432/console)**

2023-03-22 05:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1432/console)**

2023-03-22 05:32 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1432/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-03-22 05:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1433/console)**

2023-03-22 05:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1433/)<br/>**

2023-03-22 11:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1436/)<br/>**

2023-03-22 12:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1437/)<br/>**

2023-03-22 12:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1438/console)**

2023-03-22 12:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1438/)<br/>**

2023-03-23 06:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1441/)<br/>**

2023-03-23 12:22 UTC, MohanaselvamJothi requested changes

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats-toc.html
> +					<li><a href="/file-formats/DocIO/Word-document/Open-and-save-Word-document-in-ASP-NET-MVC">ASP.NET MVC</a></li>
Please change the hyperlink text as
ASP.NET MVC
ASP.NET
WPF

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-MVC.md
> +using Syncfusion.DocIO;
Mention the DocIO related namespaces alone

using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-MVC.md
> +
Add github link

You can download a complete working sample from [GitHub](https://github.com/SyncfusionExamples/DocIO-Examples/tree/main/.... ... ).

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-MVC.md
> +document.Save("Sample.docx", FormatType.Docx, HttpContext.ApplicationInstance.Response, HttpContentDisposition.Attachment);
//Save the Word document and download as attachment

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET.md
> +{% highlight c# tabtitle="C#" %}
{% highlight HTML %}

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-MVC.md
> +{% highlight c# tabtitle="C#" %}
{% highlight HTML %}

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET.md
> +
Add github link

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
> +## BlinkBinaries are missing
Revert this unwanted changes

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-WPF.md
> +
Add github link

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-MVC.md
> +**Open an existing Word document:**
Step 7 : Add below code example to **open an existing Word document in ASP.NET MVC**.

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-MVC.md
> +**Add a paragraph to the Word document:**
Step 8 : Add below code example to add a paragraph in Word document.

2023-03-23 12:22 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-MVC.md
> +**Save the Word document:**
Step 9 : Add below code example to **save the Word document in ASP.NET MVC**.

2023-03-23 12:25 UTC, MohanaselvamJothi requested changes

2023-03-23 12:25 UTC, MohanaselvamJothi commented on File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-MVC.md
> +Syncfusion Essential DocIO is a [.NET Word library](https://www.syncfusion.com/document-processing/word-framework/net/word-library) used to create, read, and edit **Word** documents programmatically
Syncfusion DocIO is a [.NET Word library](https://www.syncfusion.com/document-processing/word-framework/net/word-library) used to **create, read, and edit Word documents** programmatically without **Microsoft Word** or interop dependencies. Using this library, you can **open and save a Word document in ASP.NET MVC**.

2023-03-23 13:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1445/console)**

2023-03-23 14:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1446/console)**

2023-03-23 14:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1447/console)**

2023-03-23 14:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-65756-Open-and-Save-Presentation](https://jenkins.syncfusion.com/job/Content/job/fileformat-docs/1447/)<br/>**

2023-03-24 08:57 UTC, sharonaumao commented
After the release roll out, these changes are supposed to be in Hotfix and so I'll be closing this PR to raise another one.

2023-03-24 08:57 UTC, sharonaumao commented
After the release roll out, these changes are supposed to be in Hotfix and so I'll be closing this PR to raise another one

2023-03-24 08:57 UTC, closed without merging